# TridentNet_fast_R_101_config.yaml

_BASE_: "Base-TridentNet-Fast-C4.yaml"

DATASETS:
  TRAIN: 'coco_trash_train'
  TEST: 'coco_trash_test'

DATALOADER:
  NUM_WORKERS: 4

MODEL:
  WEIGHTS: "COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 10
    BATCH_SIZE_PER_IMAGE: 256

SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0025
  STEPS: [8000, 12000]
  MAX_ITER: 15000
  GAMMA: 0.005
  CHECKPOINT_PERIOD: 3000
  WARMUP_ITERS: 3000
  ACCUMULATION_STEPS: 2 # Gradient Accumulation steps 설정
  AMP:
    ENABLED: False
OUTPUT_DIR: "./output_tridentnet_pretrained_v4"
TEST:
  EVAL_PERIOD: 3000